CREATE TABLE IF NOT EXISTS public.account_favorite (
  favorite_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  account_id INTEGER NOT NULL,
  inv_id INTEGER NOT NULL,
  favorite_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT account_favorite_pkey PRIMARY KEY (favorite_id),
  CONSTRAINT account_favorite_account_fk
    FOREIGN KEY (account_id)
    REFERENCES public.account (account_id)
    ON DELETE CASCADE,
  CONSTRAINT account_favorite_inventory_fk
    FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id)
    ON DELETE CASCADE,
  CONSTRAINT account_favorite_account_inv_unique UNIQUE (account_id, inv_id)
);
