const pool = require("../database/")

/* ***************************
 *  Ensure saved-vehicles table exists
 * ************************** */
async function initializeFavoritesTable() {
  const sql = `
    CREATE TABLE IF NOT EXISTS public.account_favorite (
      favorite_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
      account_id INTEGER NOT NULL,
      inv_id INTEGER NOT NULL,
      favorite_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT account_favorite_pkey PRIMARY KEY (favorite_id),
      CONSTRAINT account_favorite_account_fk
        FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON DELETE CASCADE,
      CONSTRAINT account_favorite_inventory_fk
        FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id)
        ON DELETE CASCADE,
      CONSTRAINT account_favorite_account_inv_unique UNIQUE (account_id, inv_id)
    )
  `

  await pool.query(sql)
}

/* ***************************
 *  Save a vehicle to an account
 * ************************** */
async function addFavorite(account_id, inv_id) {
  try {
    const sql = `
      INSERT INTO public.account_favorite (account_id, inv_id)
      VALUES ($1, $2)
      ON CONFLICT (account_id, inv_id) DO NOTHING
      RETURNING *
    `
    const result = await pool.query(sql, [account_id, inv_id])
    return result.rows[0] || null
  } catch (error) {
    console.error("addFavorite error:", error)
    throw new Error("Unable to save the vehicle.")
  }
}

/* ***************************
 *  Remove a saved vehicle from an account
 * ************************** */
async function removeFavorite(account_id, inv_id) {
  try {
    const sql = `
      DELETE FROM public.account_favorite
      WHERE account_id = $1 AND inv_id = $2
      RETURNING *
    `
    const result = await pool.query(sql, [account_id, inv_id])
    return result.rows[0] || null
  } catch (error) {
    console.error("removeFavorite error:", error)
    throw new Error("Unable to remove the saved vehicle.")
  }
}

/* ***************************
 *  Determine whether an account has saved a vehicle
 * ************************** */
async function getFavorite(account_id, inv_id) {
  try {
    const sql = `
      SELECT *
      FROM public.account_favorite
      WHERE account_id = $1 AND inv_id = $2
    `
    const result = await pool.query(sql, [account_id, inv_id])
    return result.rows[0] || null
  } catch (error) {
    console.error("getFavorite error:", error)
    throw new Error("Unable to check the saved vehicle.")
  }
}

/* ***************************
 *  Get all saved vehicles for an account
 * ************************** */
async function getFavoritesByAccountId(account_id) {
  try {
    const sql = `
      SELECT
        af.favorite_id,
        af.favorite_created,
        i.inv_id,
        i.inv_make,
        i.inv_model,
        i.inv_year,
        i.inv_description,
        i.inv_image,
        i.inv_thumbnail,
        i.inv_price,
        i.inv_miles,
        i.inv_color,
        c.classification_name
      FROM public.account_favorite AS af
      JOIN public.inventory AS i
        ON af.inv_id = i.inv_id
      JOIN public.classification AS c
        ON i.classification_id = c.classification_id
      WHERE af.account_id = $1
      ORDER BY af.favorite_created DESC, i.inv_make, i.inv_model
    `
    const result = await pool.query(sql, [account_id])
    return result.rows
  } catch (error) {
    console.error("getFavoritesByAccountId error:", error)
    throw new Error("Unable to retrieve saved vehicles.")
  }
}

/* ***************************
 *  Count saved vehicles for an account
 * ************************** */
async function countFavoritesByAccountId(account_id) {
  try {
    const sql = `
      SELECT COUNT(*)::int AS count
      FROM public.account_favorite
      WHERE account_id = $1
    `
    const result = await pool.query(sql, [account_id])
    return result.rows[0].count
  } catch (error) {
    console.error("countFavoritesByAccountId error:", error)
    throw new Error("Unable to count saved vehicles.")
  }
}

module.exports = {
  initializeFavoritesTable,
  addFavorite,
  removeFavorite,
  getFavorite,
  getFavoritesByAccountId,
  countFavoritesByAccountId,
}
